import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { SectionTitle } from './../components/Global/SectionTitle';
import { PrimaryButton } from './../components/Global/PrimaryButton/PrimaryButton';
import { fetchWord } from '@/lang/fetchWord';
import { LanguageContext } from './../context/LangContext';
const Activation = () => {
  const { lang } = useContext(LanguageContext);
  return (
    <>
      <Head>
        <title>Verification</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-4">
        <figure className="full-image-login flex-1">
          <Image
            src="/images/login.jpg"
            alt={fetchWord('verification', lang)}
            height={500}
            width={500}
          />
        </figure>
        <div className="flex flex-col p-8 flex-1">
          <SectionTitle title={fetchWord('verification', lang)} />
          <div className="h-14" />
          <div className="flex flex-col gap-6 items-center">
            <p className="text-md">
              {fetchWord('code_activation', lang)} +0123456789
            </p>
            <div className="flex gap-4">
              <input
                className="w-32 rounded-sm h-10 border-2 border-[#E5E5E5]"
                type="tel"
              />
              <input
                className="w-32 rounded-sm h-10 border-2 border-[#E5E5E5]"
                type="tel"
              />
              <input
                className="w-32 rounded-sm h-10 border-2 border-[#E5E5E5]"
                type="tel"
              />
              <input
                className="w-32 rounded-sm h-10 border-2 border-[#E5E5E5]"
                type="tel"
              />
            </div>
            <PrimaryButton
              text={fetchWord('verify', lang)}
              classes="max-w-[300px] w-full rounded-lg !py-3 mx-auto "
            />
            <button className="text-[#5177FD] underline block text-center">
              {fetchWord('resend_code', lang)}
            </button>
          </div>
        </div>
      </div>
    </>
  );
};
export default Activation;
