import BannerLocation from "@/components/BannerLocation/BannerLocation";
import BannerSlide from "@/components/BannerSlide/BannerSlide";
import CategoriesSection from "@/components/CategoriesSection/CategoriesSection";
import { Layout } from "@/components/Layout/Layout";
import CompanyCardBox from "@/components/ServiceContainerBox/CompanyCardBox";
import Testimonial from "@/components/Testimonial/Testimonial";
import { companies } from "@/data/dummyData";
import { fetchWord } from "@/lang/fetchWord";
import Head from "next/head";
import Link from "next/link";
import { useContext } from "react";

import { LanguageContext } from "./../context/LangContext";

export default function Home() {
  const { lang } = useContext(LanguageContext);

  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        containerClassName="!block"
        full
        arrowClassName="hidden"
        extraContent={<BannerSlide />}
        extraContent2={<BannerLocation />}
        mainClassName="rounded-t-x2l -mt-5"
        hideIcons
      >
        <CategoriesSection />
        <div className="bg-bmain p-4">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-[#414B5A] font-semibold text-xl uppercase ">
              {fetchWord("categories", lang)}
            </h2>
            <Link href="/" className="uppercase text-primary font-normal">
              {fetchWord('see_all', lang)}
            </Link>
          </div>
          <div className="overflow-hidden w-full">
            <div className="flex max-w-full items-stretch">
              {companies?.slice(0, 4)?.map((company) => (
                <CompanyCardBox key={company?.name} company={company} />
              ))}
            </div>
          </div>
        </div>
        {/* <Testimonial /> */}
      </Layout>
    </>
  );
}
