import { Inter } from '@next/font/google';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import Head from 'next/head';
import Image from 'next/image';
import { products } from '@/data/cardData';

import { Banner } from './../components/Banner/Banner';
import { Layout } from './../components/Layout/Layout';
import { OfferSection } from './../components/OfferSection/OfferSection';
import { FeaturedProductSection } from './../components/FeaturedProductSection/FeaturedProductSection';
import { BrowseOurCategories } from './../components/BrowseOurCategories/BrowseOurCategories';
import { WinterCollectionBanner } from './../components/WinterCollectionBanner/WinterCollectionBanner';
import { OurFeatures } from './../components/OurFeatures/OurFeatures';
import { Brands } from './../components/Brands/Brands';
import { Testimonial } from './../components/Testimonial/Testimonial';

// const inter = Inter({ subsets: ['latin'] });

export async function getStaticProps({ locale }) {
  return {
    props: { ...(await serverSideTranslations(locale, ['home'])) },
  };
}
export default function Home(props) {
  const { t } = useTranslation('home');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <OfferSection />
        <FeaturedProductSection title="FEATURED PRODUCTS" products={products} />
        <BrowseOurCategories />
        <WinterCollectionBanner />
        <FeaturedProductSection title="New Arrivals" products={products} />
        <OurFeatures title="Our Features" center />
        <Brands />
        <Testimonial title="Testimonial" />
      </Layout>
    </>
  );
}
