import { fetchWord } from "@/lang/fetchWord";
import Head from "next/head";
import Image from "next/image";
import { useContext, useState } from "react";

import { LanguageContext } from "./../context/LangContext";
import { InputField } from "@/components/Forms/InputField";
import { Button } from "@/components/Global/Button/Button";
import Link from "next/link";
import { Layout } from "@/components/Layout/Layout";
import AuthLayout from "@/components/AuthLayout/AuthLayout";

export default function Login() {
  const { lang } = useContext(LanguageContext);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  return (
    <>
      <Head>
        <title>{fetchWord("login", lang)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <div className="flex flex-col flex-1 mt-24 items-center w-full max-w-[500px]">
          <div className="flex flex-col w-full max-w-[500px]">
            <h1 className="text-xl text-center  mb-8 capitalize">
              {fetchWord("signin", lang)}
            </h1>
            <InputField
              name="email"
              value={email}
              label={fetchWord("email", lang)}
              onChange={(e) => setEmail(e.target.value)}
            />
            <InputField
              name="password"
              value={password}
              label={fetchWord("password_label", lang)}
              onChange={(e) => setPassword(e.target.value)}
            />
            <label className="flex item-center gap-2 mb-4">
              <input
                type="checkbox"
                name="remember_me"
                value={(e) => setRememberMe(e.target.checked)}
              />
              {fetchWord("remember_me", lang)}
            </label>
            <Button classes="rounded-none">{fetchWord("signin", lang)}</Button>
            <div className="mt-8 text-center gap-1 flex justify-center font-medium">
              {fetchWord("dont_have_account", lang)}
              <Link href="/signup" className=" text-secondary">
                {fetchWord("register_now", lang)}
              </Link>
            </div>
          </div>
        </div>
      </AuthLayout>
    </>
  );
}
