import { FileUpload } from "@/components/Forms/FileUpload";
import { InputField } from "@/components/Forms/InputField";
import { Button } from "@/components/Global/Button/Button";
import { CustomerIcon, ServiceProviderIcon } from "@/components/Icons";
import CompanyIcon from "@/components/Icons/CompanyIcon";
import { Layout } from "@/components/Layout/Layout";
import { fetchWord } from "@/lang/fetchWord";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext, useState } from "react";

import { LanguageContext } from "./../context/LangContext";
import SignupTabBar from "@/components/SignupTabBar/SignupTabBar";
import SignupCustomerForm from "@/components/SignupCustomerForm/SignupCustomerForm";
import SignupServiceForm from "@/components/SignupServiceForm/SignupServiceForm";
import AuthLayout from "@/components/AuthLayout/AuthLayout";
import SignupCompanyForm from "@/components/SignupCompanyForm/SignupCompanyForm";

const tabs = ["customer", "service provider", "company"];
export default function Login() {
  const { lang } = useContext(LanguageContext);
  const [activeStage, setActiveStage] = useState("customer");
  const goNext = () => {
    let index = tabs.indexOf(activeStage);
    console.log(index);
    setActiveStage(tabs[index + 1]);
  };

  const displayTab = () => {
    switch (activeStage) {
      case "customer":
        return <SignupCustomerForm />;
      case "service provider":
        return <SignupServiceForm />;
      case "company":
        return <SignupCompanyForm />;
    }
  };
  const submit = () => {};
  return (
    <>
      <Head>
        <title>{fetchWord("register", lang)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <div className="mt-8 flex flex-col w-full max-w-[500px]">
          <h1 className="text-xl text-center font-medium mb-4 capitalize">
            {fetchWord("register", lang)}
          </h1>
          <SignupTabBar activeStage={activeStage} />
          {displayTab()}

          <Button
            classes="rounded-none"
            onClick={() => {
              if (activeStage !== "company") goNext();
              else submit("");
            }}
          >
            {activeStage === "company"
              ? fetchWord("create_account", lang)
              : fetchWord("next", lang)}
          </Button>
          <Link
            href="/login"
            className=" text-gray-400 text-sm mt-8 text-center"
          >
            {fetchWord("or_sign_in", lang)}
          </Link>
        </div>
      </AuthLayout>
    </>
  );
}
