import { fetchWord } from "@/lang/fetchWord";
import Head from "next/head";
import Image from "next/image";
import { useContext, useState } from "react";

import { LanguageContext } from "./../context/LangContext";
import { InputField } from "@/components/Forms/InputField";
import { Button } from "@/components/Global/Button/Button";
import { Layout } from "@/components/Layout/Layout";
import AuthLayout from "@/components/AuthLayout/AuthLayout";

export default function ForgotPassword() {
  const { lang } = useContext(LanguageContext);
  const [numbers, setNumbers] = useState("");
  return (
    <>
      <Head>
        <title>{fetchWord("verification", lang)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout
        hideBottomMenu
        full
        pageTitle={`${fetchWord("enter_code", lang)}`}
        description={fetchWord("enter_code_description", lang)}
      >
        <div className="flex flex-col w-full max-w-[500px] mt-12">
          <div className="flex gap-4">
            <InputField
              type="tel"
              onChange={(e) => setNumbers(e.target.value)}
              classes="!p-6"
              placeholder="2"
            />
            <InputField
              type="tel"
              onChange={(e) => setNumbers(e.target.value)}
              classes="!p-6"
              placeholder="2"
            />
            <InputField
              type="tel"
              onChange={(e) => setNumbers(e.target.value)}
              classes="!p-6"
              placeholder="2"
            />
            <InputField
              type="tel"
              onChange={(e) => setNumbers(e.target.value)}
              classes="!p-6"
              placeholder="2"
            />
          </div>
          <div className="mt-8 flex flex-col items-center">
            <p className="text-lead text-sm">{fetchWord("receive_code", lang)}</p>
            <p className="text-primary text-sm">{fetchWord("resend_code", lang)}</p>
          </div>
          <Button classes="rounded-none capitalize !p-4 text-black bg-secondary mt-14">
            {fetchWord("keep_going", lang)}
          </Button>
        </div>
      </AuthLayout>
    </>
  );
}
